name = "optimizer"
type = "webpack"
account_id = "d23423cc1d5bd44271dba1eeadd89fb7"
workers_dev = true
webpack_config = "node_modules/@ampproject-cloudflare-optimizer-scripts/dist/webpack.config.js"
vars = { MODE = "production" }
kv_namespaces = [
  { binding = "KV", id = "471b51eb82a14c4382577ca2b2f06113", preview_id="2aa2540e31a8499ebc6cb23bfcde6541"},
]

[env.dev]
name = "optimizer-dev"
vars = { MODE = "dev" }
kv_namespaces = [
  { binding = "KV", id = "a9b60f5037db4a4592e0b9208290384f", preview_id="a9b60f5037db4a4592e0b9208290384f"},
]

[env.beta]
name = "optimizer-beta"
vars = { MODE = "beta" }
kv_namespaces = [
  { binding = "KV", id = "2aa2540e31a8499ebc6cb23bfcde6541", preview_id="2aa2540e31a8499ebc6cb23bfcde6541"},
]
