{
 "title": "AMP Optimizer",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "checkpoint",
    "query": {
     "query": "label_values(transformer_duration_seconds, checkpoint)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Request / sec",
   "type": "graph",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(transformer_duration_seconds_count{checkpoint=\"overall\"}[1m]))",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "q=0.5",
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 4, "y": 1 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(transformer_duration_seconds{quantile=\"0.5\"}) by (checkpoint)",
     "legendFormat": "{{ checkpoint }}"
    }
   ]
  },
  {
   "title": "q=0.75",
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 9, "y": 1 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(transformer_duration_seconds{quantile=\"0.75\"}) by (checkpoint)",
     "legendFormat": "{{ checkpoint }}"
    }
   ]
  },
  {
   "title": "q=0.9",
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 14, "y": 1 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(transformer_duration_seconds{quantile=\"0.9\"}) by (checkpoint)",
     "legendFormat": "{{ checkpoint }}"
    }
   ]
  },
  {
   "title": "q=0.99",
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 1 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(transformer_duration_seconds{quantile=\"0.99\"}) by (checkpoint)",
     "legendFormat": "{{ checkpoint }}"
    }
   ]
  },
  { "title": "$checkpoint per pod", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 }, "repeat": "checkpoint" },
  {
   "title": "Request / sec",
   "type": "graph",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "(irate(transformer_duration_seconds_count{checkpoint=\"$checkpoint\"}[1m])) ",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "q=0.5",
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 4, "y": 10 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "transformer_duration_seconds{checkpoint=\"$checkpoint\", quantile=\"0.5\"}",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "q=0.75",
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 9, "y": 10 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "transformer_duration_seconds{checkpoint=\"$checkpoint\", quantile=\"0.75\"}",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "q=0.9",
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 14, "y": 10 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "transformer_duration_seconds{checkpoint=\"$checkpoint\", quantile=\"0.9\"}",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "q=0.99",
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 10 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "transformer_duration_seconds{checkpoint=\"$checkpoint\", quantile=\"0.99\"}",
     "legendFormat": "{{ pod }}"
    }
   ]
  }
 ]
}