#!/bin/bash

set -e

# Install npx globally for packages that use it
npm install -g npx

for d in * ; do
  if [[ ! -d "$d" || ! -e "$d/package.json" ]]; then
    continue
  fi
  pushd $d
  npm install
  popd
done
